# Generated by Django 5.0.6 on 2024-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.URLField(default='http://example.com/default_image.jpg'),
            preserve_default=False,
        ),
    ]
